### ISSUE TITLE
Python syntax highlighting got worse on new versions

### ISSUE THREAD

**Issue by KaratasFurkan** [ubolonton/tree-sitter-langs#19]
Hi, @ubolonton told me to move [the issue](https://github.com/ubolonton/emacs-tree-sitter/issues/153) here. I didn't want to upload all the images again, sharing the link to [the original issue](https://github.com/ubolonton/emacs-tree-sitter/issues/153) is enough I guess. He says highlight queries should be updated according to new grammar. Quote from him:

> This is an issue in tree-sitter-langs, probably because the grammar was updated, but the hl queries were not modified accordingly.

**Comment by shackra** [comment]
the images:

> Syntax highlighting comparison:
> 
> Without tree-sitter (variable declarations are red but less highlighting in general):
> ![disabled-cut](https://user-images.githubusercontent.com/29731420/123526258-4a727c00-d6df-11eb-9fe8-e045b863e486.png)
> 
> With old version tree-sitter (variable declarations are red and everything gets highlighting, perfect):
> ![old-cut](https://user-images.githubusercontent.com/29731420/123526266-60803c80-d6df-11eb-8335-8569a1d9a3e1.png)
> 
> With new version tree-sitter (variable declarations doesn't get highlighted):
> ![new-cut](https://user-images.githubusercontent.com/29731420/123526283-83125580-d6df-11eb-8c38-6710916279e3.png)

**Comment by ubolonton** [comment]
The highlighting of decorators that are function calls is intentional, so you probably want to keep this:
```emacs-lisp
(tree-sitter-hl-add-patterns 'python
  [(decorator (call (identifier) @function.special))])
```

**Comment by KaratasFurkan** [comment]
Thank you so much!
